#!/bin/bash


[ "$DISPLAY" ] && ( ( pacmd list-sinks | grep xrdp-sink > /dev/null ) || ( echo pulseaudio start && pulseaudio --daemon --disallow-exit=1 2> ) )

/usr/bin/google-chrome --user-data-dir=/data/browser $@


